### ISSUE TITLE
Error: Cannot read property '0' of undefined al usar myGrades

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#10]
**Describe la falla**
al usar el API myGrades aparece el error: Cannot read property '0' of undefined

**Para reproducir**
Solo usar el API myGrades

**Comportamiento esperado**
Debe regresar las calificaciones del alumno

**Pantalla**
![captura de pantalla 2018-07-25 a la s 12 02 42](https://user-images.githubusercontent.com/22565417/43218386-dcf62092-9009-11e8-9828-109e41405c3b.jpg)

**Comment by aclarturocastro** [comment]
**Este es el log del API:**

> {"level":"info","message":"group_controller  controller -- Section: mygrades -- Finding Roster ------","timestamp":"2018-07-25T17:02:21.901Z"}
> {"message":"Cannot read property '0' of undefined","stack":"TypeError: Cannot read property '0' of undefined\n    at Roster.findOne.populate.then (/usr/src/app/controllers/group_controller.js:1596:17)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)","level":"info","timestamp":"2018-07-25T17:02:21.902Z"}

**Comment by aclarturocastro** [comment]
Ya se corrigió. Dado que el grupo ahora tiene la rúbrica, este es el comportamiento por default. Sin embargo, si el grupo no tiene la rúbrica, entonces el sistema la localizará en cada bloque.
