### ISSUE TITLE
getDetails termina en error

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#124]
**Describe la falla**
Manda un error 500 

```
{
    "_id": ObjectID("5c33fbe7b4493100185efb7f"),
    "status": "open",
    "error": "TypeError: Cannot read property 'users' of undefined",
    "errorType": "TypeError",
    "controller": "user_controller",
    "section": "getDetails -- Finding User -- user: hectorramirez@aclsystems.mx",
    "stack": "TypeError: Cannot read property 'users' of undefined\n    at Object.access (/usr/src/app/shared/permissions.js:58:27)\n    at User.findOne.select.populate.populate.populate.then (/usr/src/app/controllers/user_controller.js:358:33)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)",
    "date": ISODate("2019-01-08T01:24:55.311Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
Aparentemente el "select" que le pusimos para el fiscalcurrent quitó la propiedad "perm" del objeto principal. El select al final no nos trae beneficio.

**Comment by aclarturocastro** [comment]
Reparado v1.8.6 2600b4a
