### ISSUE TITLE
error en user/modify al crear un nuevo contacto fiscal

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#126]
```
{
    "_id": ObjectID("5c3404fd2730750017912f84"),
    "status": "open",
    "error": "TypeError: Cannot read property '_id' of null",
    "errorType": "TypeError",
    "controller": "user_controller",
    "section": "modify -- Creating fiscal contact--",
    "stack": "TypeError: Cannot read property '_id' of null\n    at user.fiscal.findIndex.idx (/usr/src/app/controllers/user_controller.js:1072:39)\n    at Array.findIndex (<anonymous>)\n    at FiscalContact.create.then (/usr/src/app/controllers/user_controller.js:1071:47)\n    at process.internalTickCallback (internal/process/next_tick.js:77:7)",
    "date": ISODate("2019-01-08T02:03:41.208Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
Corrigiendo el objeto que debe usarse.

Reparado

v.1.8.7 af3d42a
