### ISSUE TITLE
Falla en el envío de correo al solicitar cambio de contraseña

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#168]
Al solicitar cambio de contraseña:

```
UnhandledPromiseRejectionWarning: Error: Unsuccessful: 400 Bad Request
    at /usr/src/app/node_modules/node-mailjet/mailjet-client.js:321:23
    at Request.callback (/usr/src/app/node_modules/superagent/lib/node/index.js:728:3)
    at parser (/usr/src/app/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.res.on (/usr/src/app/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by aclarturocastro** [comment]
v1.17.17 38d18f2
