### ISSUE TITLE
Error al generar certificado

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#170]
Aparece este error en el registro de errores:

`CastError: Cast to number failed for value \"NaN\" at path \"number\" for model \"certificates\"\n    at new CastError (/usr/src/app/node_modules/mongoose/lib/error/cast.js:29:11)\n    at SchemaNumber.cast (/usr/src/app/node_modules/mongoose/lib/schema/number.js:313:11)\n    at SchemaNumber.SchemaType.applySetters (/usr/src/app/node_modules/mongoose/lib/schematype.js:948:12)\n    at SchemaNumber.SchemaType._castForQuery (/usr/src/app/node_modules/mongoose/lib/schematype.js:1362:15)\n    at SchemaNumber.castForQuery (/usr/src/app/node_modules/mongoose/lib/schema/number.js:365:14)\n    at SchemaNumber.SchemaType.castForQueryWrapper (/usr/src/app/node_modules/mongoose/lib/schematype.js:1331:15)\n    at cast (/usr/src/app/node_modules/mongoose/lib/cast.js:307:32)\n    at model.Query.Query.cast (/usr/src/app/node_modules/mongoose/lib/query.js:4590:12)\n    at model.Query.Query._castConditions (/usr/src/app/node_modules/mongoose/lib/query.js:1783:10)\n    at model.Query.<anonymous> (/usr/src/app/node_modules/mongoose/lib/query.js:2038:8)\n    at model.Query._wrappedThunk [as _findOne] (/usr/src/app/node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)\n    at process.nextTick (/usr/src/app/node_modules/kareem/index.js:369:33)\n    at processTicksAndRejections (internal/process/task_queues.js:79:9)`

`CastError: Cast to number failed for value \"NaN\" at path \"number\" for model \"certificates\""`

Aparentemente no se generan número en los certificados.

**Comment by aclarturocastro** [comment]
Falta validar desde Libreta que el campo de folio no venga vacío.
