### ISSUE TITLE
Error 500 en notificaciones

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#42]
**Describe la falla**
Aparece error 500 en notificaciones: 

`TypeError: Cannot convert undefined or null to object\n    at /usr/src/app/controllers/notification_controller.js:153:26\n    at Array.forEach (<anonymous>)\n    at Notification.find.populate.skip.limit.lean.then (/usr/src/app/controllers/notification_controller.js:137:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7`

**Para reproducir**
correr el api "my" para ver notificaciones

**Comment by aclarturocastro** [comment]
Arreglado con v1.2.2 y commit 54ec66d
