### ISSUE TITLE
Error en group_controller

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#46]
**Describe la falla**
Apareció este error.
`TypeError: Cannot read property 'getDate' of undefined\n    at dateInSpanish (/usr/src/app/controllers/group_controller.js:3218:18)\n    at item.save.then (/usr/src/app/controllers/group_controller.js:1760:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by aclarturocastro** [comment]
Posiblemente sea causado por issue #45

**Comment by aclarturocastro** [comment]
Listo. `v1.2.6` commit 8d84cac
