### ISSUE TITLE
Arreglar API gradeByCampus

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#62]
**Describe la falla**
`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:470:11)\n    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:767:10)\n    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)\n    at Roster.find.populate.populate.populate.sort.select.then (/usr/src/app/controllers/report_controller.js:1010:24)\n    at process._tickCallback (internal/process/next_tick.js:68:7)`

Al llamar a gradeByCampus

**Comment by aclarturocastro** [comment]
v.13.15 510526d
