### ISSUE TITLE
Error al enviar el reporte de calificaciones por grupo

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#66]
`TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be one of type string or Buffer. Received type object\n    at ServerResponse.end (_http_outgoing.js:697:13)\n    at Roster.find.populate.populate.sort.select.then (/usr/src/app/controllers/report_controller.js:1168:10)`

**Comment by aclarturocastro** [comment]
v.1.4.2 0204de8
