### ISSUE TITLE
Error en notificaciones: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#88]
{
    "_id": ObjectID("5bfc2602f6e188001e484aa4"),
    "status": "open",
    "error": "TypeError: Cannot convert undefined or null to object",
    "errorType": "TypeError",
    "controller": "notification_controller",
    "section": "myNotifications -- Finding Notifications --",
    "stack": "TypeError: Cannot convert undefined or null to object\n    at /usr/src/app/controllers/notification_controller.js:174:23\n    at Array.forEach (<anonymous>)\n    at /usr/src/app/controllers/notification_controller.js:173:20\n    at Array.forEach (<anonymous>)\n    at Notification.find.populate.skip.limit.lean.then (/usr/src/app/controllers/notification_controller.js:137:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "info": "User: hectorramirez@aclsystems.mx",
    "date": ISODate("2018-11-26T16:57:38.742Z"),
    "__v": 0
}

**Comment by aclarturocastro** [comment]
v1.4.29d 5c4b5a1
