### ISSUE TITLE
Error en API /api/v1/instructor/group/create

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#90]
```
{
 "_id": ObjectID("5bdb1d1d3843f3001725ccea"),
    "status": "open",
    "error": "CastError: Cast to ObjectId failed for value \"conalep\" at path \"_id\" for model \"orgUnits\"",
    "errorType": "CastError",
    "controller": "group_controller",
    "section": "create -- Finding orgUnit --",
    "stack": "CastError: Cast to ObjectId failed for value \"conalep\" at path \"_id\" for model \"orgUnits\"\n    at new CastError (/usr/src/app/node_modules/mongoose/lib/error/cast.js:29:11)\n    at ObjectId.cast (/usr/src/app/node_modules/mongoose/lib/schema/objectid.js:156:13)\n    at ObjectId.SchemaType.applySetters (/usr/src/app/node_modules/mongoose/lib/schematype.js:763:12)\n    at ObjectId.SchemaType._castForQuery (/usr/src/app/node_modules/mongoose/lib/schematype.js:1166:15)\n    at ObjectId.SchemaType.castForQuery (/usr/src/app/node_modules/mongoose/lib/schematype.js:1156:15)\n    at ObjectId.SchemaType.castForQueryWrapper (/usr/src/app/node_modules/mongoose/lib/schematype.js:1135:15)\n    at cast (/usr/src/app/node_modules/mongoose/lib/cast.js:303:32)\n    at model.Query.Query.cast (/usr/src/app/node_modules/mongoose/lib/query.js:4019:12)\n    at model.Query.Query._castConditions (/usr/src/app/node_modules/mongoose/lib/query.js:1690:10)\n    at model.Query.Query._findOne (/usr/src/app/node_modules/mongoose/lib/query.js:1921:8)\n    at process.nextTick (/usr/src/app/node_modules/kareem/index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "date": ISODate("2018-11-01T15:34:53.767Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
v.1.4.31 6e6fb61
