### ISSUE TITLE
En api /api/v1/instructor/group/createroster

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#91]
```
{
    "_id": ObjectID("5be4d42f4a3d63001eab6e8f"),
    "status": "open",
    "error": "MongoError: E11000 duplicate key error collection: alumno.rosters index: student_1_group_1 dup key: { : ObjectId('5be4d1ab4a3d63001eab4312'), : ObjectId('5be4d297a42dbe001ee9f4f7') }",
    "errorType": "MongoError",
    "controller": "group_controller",
    "section": "createRoster -- Saving Student --",
    "stack": "MongoError: E11000 duplicate key error collection: alumno.rosters index: student_1_group_1 dup key: { : ObjectId('5be4d1ab4a3d63001eab4312'), : ObjectId('5be4d297a42dbe001ee9f4f7') }\n    at Function.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:43:12)\n    at toError (/usr/src/app/node_modules/mongodb/lib/utils.js:149:22)\n    at coll.s.topology.insert (/usr/src/app/node_modules/mongodb/lib/operations/collection_ops.js:827:39)\n    at handler (/usr/src/app/node_modules/mongodb-core/lib/topologies/replset.js:1195:22)\n    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:532:18\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "date": ISODate("2018-11-09T00:26:23.323Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
Esto evita que se duplique el roster... pero deberíamos prevenir la falla antes de crear el roster

**Comment by aclarturocastro** [comment]
v1.4.32 d4a74c1
