### ISSUE TITLE
Error: No matching document for id

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#92]
```
{
    "_id": ObjectID("5bea0f6770cd9e001ea9d743"),
    "status": "open",
    "error": "VersionError: No matching document found for id \"5be6285370cd9e001ea71e3a\" version 1 modifiedPaths \"grades, grades.14, grades.14.quests, grades.14.gradedQ\"",
    "errorType": "VersionError",
    "controller": "group_controller",
    "section": "createAttempt -- Saving Roster --",
    "stack": "VersionError: No matching document found for id \"5be6285370cd9e001ea71e3a\" version 1 modifiedPaths \"grades, grades.14, grades.14.quests, grades.14.gradedQ\"\n    at VersionError.MongooseError [as constructor] (/usr/src/app/node_modules/mongoose/lib/error/mongooseError.js:13:11)\n    at new VersionError (/usr/src/app/node_modules/mongoose/lib/error/version.js:18:17)\n    at generateVersionError (/usr/src/app/node_modules/mongoose/lib/model.js:347:10)\n    at model.Model.save (/usr/src/app/node_modules/mongoose/lib/model.js:407:27)\n    at attempt.save.then (/usr/src/app/controllers/group_controller.js:1371:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "info": "Roster: 5be6285370cd9e001ea71e3a User: ebasurto1517@gro.conalep.edu.mx Quest: {\"answers\":[{\"idquestion\":\"5a8e14894badc7001c71d22b\",\"result\":[{\"answer\":1,\"type\":\"option\",\"index\":0,\"indexquestions\":0}]},{\"idquestion\":\"5a8e14894badc7001c71d229\",\"result\":[{\"answer\":\"true\",\"type\":\"tf\",\"index\":1,\"indexquestions\":1}]},{\"idquestion\":\"5a8e14894badc7001c71d227\",\"result\":[{\"answer\":\"true\",\"type\":\"tf\",\"index\":2,\"indexquestions\":2}]},{\"idquestion\":\"5a8e14894badc7001c71d225\",\"result\":[{\"answer\":\"false\",\"type\":\"tf\",\"index\":3,\"indexquestions\":3}]},{\"idquestion\":\"5a8e14894badc7001c71d223\",\"result\":[{\"answer\":\"true\",\"type\":\"tf\",\"index\":4,\"indexquestions\":4}]},{\"idquestion\":\"5a8e14894badc7001c71d221\",\"result\":[{\"answer\":\"true\",\"type\":\"tf\",\"index\":5,\"indexquestions\":5}]},{\"idquestion\":\"5a8e14894badc7001c71d21f\",\"result\":[{\"answer\":\"true\",\"type\":\"tf\",\"index\":6,\"indexquestions\":6}]}],\"grade\":85.71428571428572,\"attempt\":\"Mon Nov 12 2018 23:40:23 GMT+0000 (Coordinated Universal Time)\"}",
    "date": ISODate("2018-11-12T23:40:23.200Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
Aquí al parecer se realiza una modificación al documento en el momento mismo en que mongo quiere guardarlo. 

Posibles causas: 

- Alguien más está conectado y está realizando una acción al mismo tiempo
- Se tienen abiertas dos sesiones a la vez...

**Comment by aclarturocastro** [comment]
v1.4.34a 85e0844
