### ISSUE TITLE
TypeError: Cannot set property 'beginDate' of undefined en nextBlock

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#93]
```
{
    "_id": ObjectID("5bece8b4b415db001e29b363"),
    "status": "open",
    "error": "TypeError: Cannot set property 'beginDate' of undefined",
    "errorType": "TypeError",
    "controller": "group_controller",
    "section": "nextBlock -- Finding Roster --",
    "stack": "TypeError: Cannot set property 'beginDate' of undefined\n    at Roster.findOne.populate.then (/usr/src/app/controllers/group_controller.js:2483:48)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "info": "User: andradevazquezmarioalejandro@gmail.com Userid: 5beb92fde7e62c001dbc9adb GroupId: 5beb93359a0347001ed67303 BlockId: 5a8f0c93f28b63001bd58062",
    "date": ISODate("2018-11-15T03:32:04.607Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
v1.4.33 cf53a8a
