### ISSUE TITLE
No se está validando el TEXT en la creación de la discusión.

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#95]
{
    "_id": ObjectID("5bea46c84cbe5c001e935e8d"),
    "status": "open",
    "error": "ValidationError: text: Path `text` is required.",
    "errorType": "ValidationError",
    "controller": "discussion_controller",
    "section": "create -- Creating comment -- User: dulcinea1206@hotmail.com text: ",
    "stack": "ValidationError: discussions validation failed: text: Path `text` is required.\n    at new ValidationError (/usr/src/app/node_modules/mongoose/lib/error/validation.js:30:11)\n    at model.Document.invalidate (/usr/src/app/node_modules/mongoose/lib/document.js:2026:32)\n    at p.doValidate.skipSchemaValidators (/usr/src/app/node_modules/mongoose/lib/document.js:1889:17)\n    at /usr/src/app/node_modules/mongoose/lib/schematype.js:847:9\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "date": ISODate("2018-11-13T03:36:40.474Z"),
    "__v": 0
}

**Comment by aclarturocastro** [comment]
Al momento de crear la discusión, no le ponen el texto del mensaje y me imagino que no les avisa nada...

**Comment by aclarturocastro** [comment]
v1.4.35 85e0844

**Comment by aclarturocastro** [comment]
Faltaría que de lado de ángular también validara que ese campo no viniera vacío
