### ISSUE TITLE
Error al momento de obtener discusiones CastError: Cast to ObjectId failed for value \"undefined\" at path \"block\" for model \"discussions\""

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#96]
```
{
    "_id": ObjectID("5bef8f1d9a0347001ee5ae4c"),
    "status": "open",
    "error": "CastError: Cast to ObjectId failed for value \"undefined\" at path \"block\" for model \"discussions\"",
    "errorType": "CastError",
    "controller": "discussion_controller",
    "section": "get -- Getting comment --",
    "stack": "CastError: Cast to ObjectId failed for value \"undefined\" at path \"block\" for model \"discussions\"\n    at new CastError (/usr/src/app/node_modules/mongoose/lib/error/cast.js:29:11)\n    at ObjectId.cast (/usr/src/app/node_modules/mongoose/lib/schema/objectid.js:156:13)\n    at ObjectId.SchemaType.applySetters (/usr/src/app/node_modules/mongoose/lib/schematype.js:763:12)\n    at ObjectId.SchemaType._castForQuery (/usr/src/app/node_modules/mongoose/lib/schematype.js:1166:15)\n    at ObjectId.SchemaType.castForQuery (/usr/src/app/node_modules/mongoose/lib/schematype.js:1156:15)\n    at ObjectId.SchemaType.castForQueryWrapper (/usr/src/app/node_modules/mongoose/lib/schematype.js:1135:15)\n    at cast (/usr/src/app/node_modules/mongoose/lib/cast.js:303:32)\n    at model.Query.Query.cast (/usr/src/app/node_modules/mongoose/lib/query.js:4019:12)\n    at model.Query.Query._castConditions (/usr/src/app/node_modules/mongoose/lib/query.js:1690:10)\n    at model.Query.Query._find (/usr/src/app/node_modules/mongoose/lib/query.js:1705:8)\n    at process.nextTick (/usr/src/app/node_modules/kareem/index.js:369:33)\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "date": ISODate("2018-11-17T03:46:37.319Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
Tengo la sospecha que en el `query` se va el block como vacío o null... y eso hace que mande error...

**Comment by aclarturocastro** [comment]
Le puse un validador, para que si detecta block vacío lo quite para que no haya error.

v1.4.36 7035e4e
