### ISSUE TITLE
Error en envío de resultado para user_controller

### ISSUE THREAD

**Issue by aclarturocastro** [ACLSystems/alumno#97]
```
{
    "_id": ObjectID("5bf462776fb687001eb205b1"),
    "status": "open",
    "error": "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client",
    "errorType": "Error [ERR_HTTP_HEADERS_SENT]",
    "controller": "user_controller",
    "section": "myRoles -- Finding Ous --",
    "stack": "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at ServerResponse.setHeader (_http_outgoing.js:470:11)\n    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:767:10)\n    at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)\n    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)\n    at OrgUnit.find.select.lean.then (/usr/src/app/controllers/user_controller.js:1182:29)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "date": ISODate("2018-11-20T19:37:27.782Z"),
    "__v": 0
}
```

**Comment by aclarturocastro** [comment]
1.4.37c 3dd08bf
